# To test if your modification to this file works, go to http://lint.travis-ci.org/.
language: node_js
node_js:
  - '6.9'
os:
  - linux
script:
  - npm run test
after_success:
  - npm run coveralls
addons:
    code_climate:
        repo_token: 189f6b7e6a00335fd185af20a0ae3a620468485e915b8c531b3b4cce7ee75f5c
